#!/bin/sh

## This Source Code Form is subject to the terms of the Mozilla Public
## License, v. 2.0. If a copy of the MPL was not distributed with this
## file, You can obtain one at https://mozilla.org/MPL/2.0/.

: "${USER_ID:=$(stat -c%u .)}"
: "${GROUP_ID:=$(stat -c%g .)}"
: "${GROUP_NAME:=${USER_NAME:=ledobe}}"

main() {
	groupadd -g "$GROUP_ID" "$GROUP_NAME" || exit
	useradd -lmg "$GROUP_NAME" -u "$USER_ID" "$USER_NAME" || exit
	home="$(getent passwd "$USER_ID" | cut -d: -f6)"

	mount=/mnt/home
	## Move the all the newly-created home dir contents to the mounted dir.
	find "$home" -mindepth 1 -maxdepth 1 -exec \
		mv -ut "$mount" {} +
	## Substitute the created home dir with the mounted one.
	rm -rf "$home"
	ln -s "$mount" "$home"

	## Add to home dir what was created for it during the image build.
	unbundleHome /home/.ledobe "$home"

	## Update build dir with what was created for it during the image build.
	mvru "${home}/build" /build

	# shellcheck disable=SC1091
	## Set up NPM to work off the home dir instead of node installation dir.
	HOME="$home" . /etc/profile.d/home-npm.sh

	if [ "$(command -v "$1")" ]; then
		execGosu "$@"
	elif [ $# -eq 1 ]; then
		execGosu sh -c "$1"
	else
		echo "$@" | execGosu sh -s
	fi
}

## Add to home dir what was created for it during the image build.
unbundleHome() { ## (bundledHome home)
	bundledHome="$1"
	home="$2"

	bundled="$(mktemp)"
	untouched="$(mktemp)"
	chownables="$(mktemp)"
	## Record what was bundled for the home dir during the image build.
	## TODO Move this to the image build time.
	findNonUser "$bundledHome" > "$bundled"
	## Update home dir with the bundled contents.
	mvru "$bundledHome" "$home"
	## Record which home dir files were NOT updated from the bundled ones.
	findNonUser "$bundledHome" > "$untouched"
	## Record which home dir files need to be `chown`ed now.
	comm -z23 "$bundled" "$untouched" > "$chownables"
	## Force the bundled contents of home dir to be owned by the user.
	(
		cd "$home" || exit
		xargs -0a "$chownables" -I {} chown "$USER_ID:$GROUP_ID" {}
	)
	rm "$bundled" "$untouched" "$chownables"
}

## Output null-separated list of files that are not owned by USER_ID.
findNonUser() ( ## (directory)
	cd "$1" || exit
	find . -mindepth 1 -not -user "$USER_ID" -print0 \
		| sort -z
)

## A recursive "mv -u", like "cp -ru" but moving instead of copying.
mvru() { ## (source target)
	if [ ! -d "$1" ] || [ ! -e "$2" ]; then
		mv -u "$1" "$2" || exit
		return
	fi
	for entry in "$1/"* "$1/."[!.]* "$1/.."?*; do
		if [ -e "$entry" ]; then
			mvru "$entry" "$2/${entry##"$1/"}"
		fi
	done
}

## Replace the shell with the given command running as USER_ID.
execGosu() { ## (command arguments ...)
	exec gosu "$USER_ID" "$@"
}

main "$@"
